name: foxscript311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai
    - weaviate-client
    - langchain
    - langchain-openai
    - langchain-experimental
    - langchain-community
    - tiktoken
    - faiss-cpu
    - selenium
    - beautifulsoup4
    - lxml
    - PyPDF2
    - boto3
    - python-dotenv
    - tenacity
    - pyyaml
    - pandas
    - tabulate
    - unstructured
    - newspaper3k
    - unittest-parametrize
    - fake-useragent
    - unittest-parametrize
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - pypandoc
    - pyjwt
    
